# DOCKER-VERSION 1.2.0

FROM    ubuntu:14.04

# Update repository package lists
RUN     apt-get update

# Install NodeJS
RUN     apt-get install nodejs -y

# Install npm
RUN     apt-get install npm -y
